### ISSUE TITLE
一加3t手机，magisk root，下载后未做任何设置，直接运行main.js便利到排名最后结束时程序会崩溃报错

### ISSUE THREAD

**Issue by Tumplr** [Nick-Hopps/Ant-Forest-autoscript#21]
Version: 256
Android: 26
java.lang.RuntimeException: android.view.InflateException: android.view.InflateException: java.lang.ClassNotFoundException: android.widget.card
 at com.stardust.autojs.core.ui.ConvertLayoutInflater.inflate(ConvertLayoutInflater.java:32)
 at com.stardust.autojs.runtime.api.Floaty.lambda$inflate$0$Floaty(Floaty.java:70)
 at com.stardust.autojs.runtime.api.Floaty$$Lambda$0.run(Unknown Source:6)
 at android.os.Handler.handleCallback(Handler.java:789)
 at android.os.Handler.dispatchMessage(Handler.java:98)
 at android.os.Looper.loop(Looper.java:164)
 at android.app.ActivityThread.main(ActivityThread.java:6798)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
Caused by: android.view.InflateException: android.view.InflateException: java.lang.ClassNotFoundException: android.widget.card
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.inflate(DynamicLayoutInflater.java:142)
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.inflate(DynamicLayoutInflater.java:127)
 at com.stardust.autojs.core.ui.ConvertLayoutInflater.inflate(ConvertLayoutInflater.java:29)
 ... 10 more
Caused by: android.view.InflateException: java.lang.ClassNotFoundException: android.widget.card
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.createViewForName(DynamicLayoutInflater.java:212)
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.inflate(DynamicLayoutInflater.java:155)
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.inflate(DynamicLayoutInflater.java:140)
 ... 12 more
Caused by: java.lang.ClassNotFoundException: android.widget.card
 at java.lang.Class.classForName(Native Method)
 at java.lang.Class.forName(Class.java:453)
 at java.lang.Class.forName(Class.java:378)
 at com.stardust.autojs.core.ui.inflater.DynamicLayoutInflater.createViewForName(DynamicLayoutInflater.java:202)
 ... 14 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.widget.card" on path: DexPathList[[zip file "/data/app/com.stardust.scriptdroid-XnwwJVYpMxC-liUHwRahBQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.stardust.scriptdroid-XnwwJVYpMxC-liUHwRahBQ==/lib/arm, /system/fake-libs, /data/app/com.stardust.scriptdroid-XnwwJVYpMxC-liUHwRahBQ==/base.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
 ... 18 more

**Comment by Tumplr** [comment]
auto.js去QQ群下载4.1.0解决一切
