### ISSUE TITLE
4.0.5版本的autojs运行，打开排行榜就报错

### ISSUE THREAD

**Issue by Tumplr** [Nick-Hopps/Ant-Forest-autoscript#22]
02:25:51.308/E: Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null (file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js#289)
Wrapped java.lang.IllegalStateException: nodeInfo.viewIdResourceName must not be null
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:289:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:323:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:340:0
    at /storage/emulated/0/脚本/Ant-Forest-autoscript-master/main.js:35:0

**Comment by Tumplr** [comment]
auto.js去QQ群下载4.1.0解决一切
