### ISSUE TITLE
解锁失败

### ISSUE THREAD

**Issue by pb8DvwQkfRR** [Nick-Hopps/Ant-Forest-autoscript#93]
日志如下：
18:47:01.373/E: Cannot convert org.mozilla.javascript.NativeArray@917765 to int[][] (<init>#30)
Cannot convert org.mozilla.javascript.NativeArray@917765 to int[][]
    at <init>:30:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js:137:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js:150:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/lib/Unlock.js:162:0
    at file:/storage/emulated/0/脚本/Ant-Forest-autoscript-master/core/Ant_forest.js:689:0
    at /storage/emulated/0/脚本/Ant-Forest-autoscript-master/main.js:53:0
使用了https://github.com/Nick-Hopps/Ant-Forest-autoscript/issues/31 的解锁方法
小米8 MIUI.eu beta 9.6.27

**Comment by pb8DvwQkfRR** [comment]
使用了最新的Ant_forest.js覆盖后解决。
